vich_uploader:
  db_driver: orm

  mappings:
    plat_image:
      uri_prefix: /images/plats
      upload_destination: '%kernel.project_dir%/public/images/plats'
      namer: Vich\UploaderBundle\Naming\UniqidNamer
